version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: rt-basic-archi-mongodb-dev
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: rt_basic_archi_dev
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - backend-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  backend-network:
    driver: bridge
